In [2]:
import numpy as np

In [7]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr1)
arr1@arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [4]:
np.dot(arr1, arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [8]:
np.dot(arr1, arr2.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [15]:
arr1 = np.arange(1,13)
arr2 = np.arange(1,10)
print(arr1@arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [4]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(3)

arr1.T - arr2

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

In [1]:
import numpy as np

np.random.random((3, 3))

array([[0.16771087, 0.92118012, 0.51159139],
       [0.77370096, 0.54928999, 0.54361283],
       [0.14935368, 0.50056344, 0.33428217]])

In [2]:
import numpy as np
import scipy as sp
mat1 = np.arange(1, 13).reshape((3, 4))
mat2 = np.ones(9).reshape((3,3))
sp.signal.convolve(mat1, mat2, "valid")

array([[54., 63.]])

In [7]:
mat3 = np.arange(1, 25).reshape((2,3,4))

mat3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [51]:
num_filter = 3
kernel_size = (3,3)
stride = 2
padding = 1
n_channels = 3
weights = np.random.randn(num_filter, n_channels,*kernel_size)
biases = np.random.randn(num_filter)
input = None
output = None
input_padded = None

In [52]:
row = 5
cols = 5
batch_size = 2
input = np.random.randn(batch_size, n_channels,row, cols)
input


array([[[[-0.81936614, -0.24200816, -1.19256164,  1.40125863,
           1.67646243],
         [ 0.25715611,  0.51513027,  2.18946655, -0.06640023,
          -0.50173168],
         [ 0.51887138,  0.59468809, -0.3714143 , -0.47715862,
           1.59513974],
         [ 0.89773427, -1.23253664,  3.18596911, -0.29458732,
           0.73859799],
         [-2.16489822, -0.48999919, -2.24804261,  0.66145544,
          -0.99837207]],

        [[ 0.65172439, -0.52674415,  0.81381309,  2.34503397,
           0.75258697],
         [ 0.0512744 , -0.76841714, -1.1651662 , -0.17690113,
           0.03229236],
         [ 0.89980069, -1.28973432,  1.41027578, -1.13912803,
           1.00741999],
         [-1.41616572, -0.31451381,  0.80598681,  0.63490699,
          -1.81621171],
         [-0.29735088,  0.69289712,  0.38187456,  0.75766563,
           0.22829801]],

        [[ 1.35760598, -0.95914529,  0.19619684,  0.45681916,
           0.79313887],
         [-1.58923401, -0.00963078, -1.88174572,  

In [53]:
output_shape = (num_filter, int((row + 2*padding - kernel_size[0])/stride + 1), int((cols + 2*padding - kernel_size[1])/stride + 1))

output =  np.zeros( output_shape)
output

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
output_grad = np.random.randn(*output_shape)

In [55]:
input_padded = np.zeros((batch_size,n_channels, row + 2*padding, cols + 2*padding))
input_padded[:,:, padding:row + padding , padding:cols + padding] = input
input_padded

array([[[[ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ],
         [ 0.        , -0.81936614, -0.24200816, -1.19256164,
           1.40125863,  1.67646243,  0.        ],
         [ 0.        ,  0.25715611,  0.51513027,  2.18946655,
          -0.06640023, -0.50173168,  0.        ],
         [ 0.        ,  0.51887138,  0.59468809, -0.3714143 ,
          -0.47715862,  1.59513974,  0.        ],
         [ 0.        ,  0.89773427, -1.23253664,  3.18596911,
          -0.29458732,  0.73859799,  0.        ],
         [ 0.        , -2.16489822, -0.48999919, -2.24804261,
           0.66145544, -0.99837207,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.65172439, -0.52674415,  0.81381309,
           2.34503397,  0.75258697,  0. 

In [56]:
for i in range(0, row + 2*padding - kernel_size[0] + 1, stride):
            for j in range(0, cols + 2*padding - kernel_size[1] + 1, stride):
                req_mat = input_padded[:,:, i:i+kernel_size[0], j:j+kernel_size[1]]   
                req_mat = np.sum(req_mat *weights, axis = (1,2,3)) + biases
                print(req_mat)                 
                output[:, int(i/stride), int(j/stride)] = req_mat
                
output

ValueError: operands could not be broadcast together with shapes (2,3,3,3) (3,3,3,3) 

In [62]:
a1 = np.ones(12).reshape(2, 2, 3)
a2 = np.ones(6).reshape(2, 3) * 2

a1 * a2
# a2

array([[[2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.]]])

In [13]:
import numpy as np

a1 = np.ones(15).reshape(3, 5)
a2 = np.ones(3)
a3 = np.ones(5)
np.array([a2]).T @ np.array([a3])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
a1 = np.ones(15)
a2 = np.ones(240).reshape(15, 16)
a1 @ a2

array([15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15.])