In [2]:
import numpy as np

In [7]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr1)
arr1@arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [4]:
np.dot(arr1, arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [8]:
np.dot(arr1, arr2.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [15]:
arr1 = np.arange(1,13)
arr2 = np.arange(1,10)
print(arr1@arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [4]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(3)

arr1.T - arr2

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])