In [1]:
%run setup.env

In [21]:
# Assuming your RNNCell class is already defined as provided
from algorithms.nn.layers import RNNCell
from algorithms.nn.activations import softmax

# Initialize the RNN cell
input_size = vocab_size
hidden_size = 10  # Number of hidden units
output_size = vocab_size
rnn = RNNCell(input_size, hidden_size, output_size, final_activation=softmax)

# Training the RNN
epochs = 100
learning_rate = 0.01

for epoch in range(epochs):
    # Forward pass
    output = rnn.forward(inputs)
    
    # print(output)
    # Calculate loss (cross-entropy)
    loss = -np.sum(targets[-1] * np.log(output + 1e-8))  # Add a small value to avoid log(0)
    # Calculate gradient of the loss with respect to the output
    output_grad = output - targets[-1]
    # Backward pass
    rnn.backward(output_grad, learning_rate)
    
    if epoch % 10 == 0:
        print(f'Epoch {epoch}, Loss: {loss:.4f}')

# Testing the RNN
test_input = [one_hot_encode('h', vocab_size)]
predicted_output, _ = rnn.forward_one(test_input[0])
predicted_char = ix_to_char[np.argmax(predicted_output)]
print(f'Predicted next character: {predicted_char}')


[[ 0.00564235  0.08069242  0.38756324  0.32411825  0.05426007 -0.98825571
   0.10283053  0.03314885]]
(1, 10) (1, 8)


ValueError: non-broadcastable output operand with shape (10,8) doesn't match the broadcast shape (10,10,8)

In [ ]:
inputs

[array([1., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0.])]